[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "dns-shark"
publish = false
version = "0.0.0"

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
serde_with = "3.5.1"
