name: CI

on:
  pull_request:
    branches: [main]
  merge_group:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t dns-shark .

      - name: Run tests
        run: docker run --rm -t dns-shark cargo t
